# give travis super user perms
sudo: required

services:
    - docker

before_install:
    - docker build -t samsam489/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true samsam489/docker-react npm run test    

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-329621337808"
    bucket_path: "docker-react"
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
