# give travis super user perms
sudo: required

services:
    - docker

before_install:
    - docker build -t samsam489/docker-react -f Dockerfile.dev .

script:
     - docker run -e CI=true samsam489/docker-react npm run test    