FROM node:alpine

ENV http_proxy="http://httpproxy.bfm.com:8080"  \
    https_proxy="http://sftpproxy.bfm.com:8080"

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]
